// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */

import { c } from 'hyperschema/runtime'

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @autobonk/writer
const encoding0 = {
  preencode (state, m) {
    c.buffer.preencode(state, m.key)
  },
  encode (state, m) {
    c.buffer.encode(state, m.key)
  },
  decode (state) {
    const r0 = c.buffer.decode(state)

    return {
      key: r0
    }
  }
}

// @autobonk/invite
const encoding1 = {
  preencode (state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
  },
  encode (state, m) {
    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
  },
  decode (state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: r0,
      invite: r1,
      publicKey: r2,
      expires: r3
    }
  }
}

// @room/message
const encoding2 = {
  preencode (state, m) {
    c.uint.preencode(state, m.index)
    state.end++ // max flag is 1 so always one byte

    if (m.text) c.string.preencode(state, m.text)
  },
  encode (state, m) {
    const flags = m.text ? 1 : 0

    c.uint.encode(state, m.index)
    c.uint.encode(state, flags)

    if (m.text) c.string.encode(state, m.text)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      index: r0,
      text: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @room/send-message
const encoding3 = {
  preencode (state, m) {
    c.string.preencode(state, m.text)
  },
  encode (state, m) {
    c.string.encode(state, m.text)
  },
  decode (state) {
    const r0 = c.string.decode(state)

    return {
      text: r0
    }
  }
}

// @autobonk/invite/hyperdb#0
const encoding4 = {
  preencode (state, m) {
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
  },
  encode (state, m) {
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
  },
  decode (state) {
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: null,
      invite: r1,
      publicKey: r2,
      expires: r3
    }
  }
}

// @autobonk/writer/hyperdb#1
const encoding5 = {
  preencode (state, m) {

  },
  encode (state, m) {

  },
  decode (state) {
    return {
      key: null
    }
  }
}

// @room/message/hyperdb#2
const encoding6 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.text) c.string.preencode(state, m.text)
  },
  encode (state, m) {
    const flags = m.text ? 1 : 0

    c.uint.encode(state, flags)

    if (m.text) c.string.encode(state, m.text)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      index: 0,
      text: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

function setVersion (v) {
  version = v
}

function encode (name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode (name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum (name) {
  switch (name) {
    default: throw new Error('Enum not found ' + name)
  }
}

function getEncoding (name) {
  switch (name) {
    case '@autobonk/writer': return encoding0
    case '@autobonk/invite': return encoding1
    case '@room/message': return encoding2
    case '@room/send-message': return encoding3
    case '@autobonk/invite/hyperdb#0': return encoding4
    case '@autobonk/writer/hyperdb#1': return encoding5
    case '@room/message/hyperdb#2': return encoding6
    default: throw new Error('Encoder not found ' + name)
  }
}

function getStruct (name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode (state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode (state, m) {
      version = v
      enc.encode(state, m)
    },
    decode (state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
